#!/usr/bin/env bash

# Edit these two
IN_GAME_SATURATION=1000
DEFAULT_SATURATION=$(nvidia-settings -q DigitalVibrance | grep -Eo "[0-9]{2,}+" | head -n 1)

nvidia-settings -a DigitalVibrance=$IN_GAME_SATURATION
"$@"
nvidia-settings -a DigitalVibrance=$DEFAULT_SATURATION
